"""Remove foreign key from orders

Revision ID: 33a9b4661dd2
Revises: 70d224a2d17d
Create Date: 2024-08-08 06:17:41.611888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a9b4661dd2'
down_revision = '70d224a2d17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'total_price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_orders_product_id', table_name='orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_orders_product_id', 'orders', ['product_id'], unique=False)
    op.alter_column('orders', 'total_price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
