"""Update OrderModel to remove foreign keys

Revision ID: 6400839a219d
Revises: 892ad900733a
Create Date: 2024-08-11 10:43:36.091848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func

# revision identifiers, used by Alembic.
revision = '6400839a219d'
down_revision = '892ad900733a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_date', sa.DateTime(), nullable=False, server_default=func.now()))
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=False, server_default="0"))  # Replace with a suitable default
    op.add_column('orders', sa.Column('vendor_id', sa.Integer(), nullable=False, server_default="0"))  # Replace with a suitable default
    op.alter_column('orders', 'tracking_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Pending'::character varying"))
    
    # Remove the default now that the column is populated
    op.alter_column('orders', 'order_date', server_default=None)
    op.alter_column('orders', 'user_id', server_default=None)
    op.alter_column('orders', 'vendor_id', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'tracking_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Pending'::character varying"))
    op.drop_column('orders', 'vendor_id')
    op.drop_column('orders', 'user_id')
    op.drop_column('orders', 'order_date')
    # ### end Alembic commands ###
