"""added new variables

Revision ID: 70d224a2d17d
Revises: 51679d73ba63
Create Date: 2024-08-08 05:27:25.307295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d224a2d17d'
down_revision = '51679d73ba63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('total_price', sa.Integer(), nullable=False))
    op.alter_column('orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_orders_item_name', table_name='orders')
    op.drop_column('orders', 'item_name')
    op.create_index('ix_orders_product_id', 'orders', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_product_id', table_name='orders')
    op.add_column('orders', sa.Column('item_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_orders_item_name', 'orders', ['item_name'], unique=False)
    op.alter_column('orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'total_price')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###
