"""Added order tracking

Revision ID: 892ad900733a
Revises: 9968ad1ecb4d
Create Date: 2024-08-09 05:41:24.115969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892ad900733a'
down_revision = '9968ad1ecb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_status', sa.String(), nullable=False, server_default="Pending"))
    op.add_column('orders', sa.Column('tracking_info', sa.String(), nullable=True))
    op.alter_column('orders', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('orders', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('orders', 'tracking_info')
    op.drop_column('orders', 'tracking_status')
    # ### end Alembic commands ###
